language: python

services:
  - postgresql

python:
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DATABASE_URL="postgres://postgres@localhost:5432/gardenhub"

install:
  - pip install -r requirements.txt
  - pip install coveralls

before_script:
  - psql -c 'create database gardenhub;' -d postgres -U postgres

script:
  - python manage.py test
  - coverage run manage.py test

after_success: coveralls
