sudo: required

services:
  - docker

before_script:
  - docker build -t gardenhub .
  - docker run --name db -e POSTGRES_PASSWORD=gardenhub -d postgres:10-alpine && sleep 5
  - docker run -it --name gardenhub --link db:postgres -e CI -e TRAVIS -e TRAVIS_JOB_ID -e TRAVIS_PULL_REQUEST -e DATABASE_URL="postgres://postgres:gardenhub@db:5432/postgres" -d gardenhub sh
  - docker exec gardenhub pip install coverage coveralls

script:
  - docker exec gardenhub coverage run --source='.' manage.py test gardenhub

after_success:
  - apk add git
  - docker exec gardenhub coveralls

notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGFsZXhnbGVhc29uJTNBbWF0cml4Lm9yZy8lMjFPVXNkbEF3Z09Cc09PR0hwUVYlM0FtYXRyaXgub3Jn"
        on_success: change  # always|never|change
        on_failure: change
        on_start: never
